name: KiipCraft
version: 2.0
author: Thunderkookie15
main: me.Lucas.KiipCraft.Main
api-version: 1.15
description: De KiipCraft Plugin.

commands:
  kiipcraft:
    aliases:
      - kcs
    description: Laat de plugin commands zien.