name: KiipCraft
version: 2.0
author: Thunderkookie15
main: me.Lucas.KiipCraft.Main
api-version: 1.15
description: De KiipCraft plugin voor de Shops en Events.

commands:
  kiipcraft:
    description: Laat de plugin commands zien.